# --- Required site URLs (needed for absolute links) ---
url: "https://estellegueville.com"
baseurl: ""        # leave empty with a custom domain

# --- Site identity ---
title: Estelle Guéville, Yale University
author: Estelle Guéville

# --- Navbar (English) ---
navbar-links:
  About Me: 
    - My Research Interests: "about"
    - My Career in GLAM: "glam"
    - My PhD: "thesis"
  Research and DH:
    - The Paris Bible Project: "https://parisbible.github.io/"
    - Medieval Distant Viewing: "medievaldistantviewing"
    - Understanding Medieval Manuscripts Gilding Techniques: "gildingtechniques"
    - Mapping the Blue Qur'an: "https://estellegvl.github.io/bluequran/"
    - Uprooted. The New Haven Time Capsule : "https://uprootedtimecapsule.github.io/"
  Publications: 
    - Publications: "publications"
    - Conferences: "conferences"
  CV: "cv"
  Contact: "contact"

# --- Navbar (French) ---
navbar-links-fr:
  À propos de moi:
    - Mes axes de recherche: "about"
    - Mon parcours GLAM: "glam"
    - Ma thèse: "thesis"
  Recherches:
    - The Paris Bible Project: "https://parisbible.github.io/"
    - Medieval Distant Viewing: "medievaldistantviewing"
    - Understanding Medieval Manuscripts Gilding Techniques: "gildingtechniques"
    - Mapping the Blue Qur'an: "https://estellegvl.github.io/bluequran/"
    - Uprooted. The New Haven Time Capsule: "https://uprootedtimecapsule.github.io/"
  Publications:
    - Publications: "publications"
    - Conférences: "conferences"    # NOTE: lowercase slug
  CV: "cv"                          # NOTE: lowercase slug
  Contact: "contact"

# --- Blog pagination path ---
paginate_path: "/blog/page:num/"

# --- Avatar / Logo ---
avatar: "/assets/img/2022_Identity_EGE.jpg/"
round-avatar: true
# title-img: /path/to/image   # (optional)

# --- Social links (footer) ---
social-network-links:
  email: "estelle.gueville@yale.edu"
  github: EstelleGvl
  linkedin: estellegueville
  instagram: estelle_gvl
  ORCID: 0000-0003-2603-1051
  google-scholar: https://scholar.google.fr/citations?user=sgoJus8AAAAJ&hl=fr

# --- Sharing ---
share-links-active:
  twitter: true
  facebook: false
  linkedin: true
  vk: false

# --- Excerpts / SEO bits ---
excerpt_length: 50
#keywords: "my,list,of,keywords"

# --- Theme colors ---
navbar-col: "#000000"
navbar-text-col: "#EAEAEA"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#000000"
footer-text-col: "#EAEAEA"
footer-link-col: "##404040"   # (note: you have a double # here; keep if intentional)

# --- Build settings ---
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# --- Defaults ---
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

# --- Exclusions ---
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

# --- Plugins (GitHub Pages friendly) ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189